CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullName VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    course VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    studentId VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);
